from functools import reduce

import pandas as pd

columns = {'AdrActCnt': 'The sum count of unique addresses that were active in the network (either as a recipient or originator of a ledger change) that interval. All parties in a ledger change action (recipients and originators) are counted. Individual addresses are not double-counted if previously active.',
           'CapRealUSD': 'The sum USD value based on the USD closing price on the day that a native unit last moved (i.e., last transacted) for all native units.',
           'DiffMean': 'The mean difficulty of finding a hash that meets the protocol-designated requirement (i.e., the difficulty of finding a new block) that interval. The requirement is unique to each applicable cryptocurrency protocol. Difficulty is adjusted periodically by the protocol as a function of how much hashing power is being deployed by miners.',
           'FeeTotUSD': 'The sum USD value of all fees paid by transactors that interval. Fees do not include new issuance.',
           'HashRate': 'The mean rate at which miners are solving hashes that interval. Hash rate is the speed at which computations are being completed across all miners in the network. The unit of measurement varies depending on the protocol.',
           'PriceUSD': 'The fixed closing price of the asset as of 00:00 UTC the following day (i.e., midnight UTC of the current day) denominated in USD. This price is generated by Coin Metrics fixing/reference rate service. Real-time PriceUSD is the fixed closing price of the asset as of the timestamp set by the blocks miner.',
           'RevHashRateUSD': 'The USD value of the mean daily miner reward per estimated hash unit per second performed during the period, also known as hashprice. The unit of hashpower measurement depends on the protocol.',
           'VtyDayRet30d': 'The 30D volatility, measured as the standard deviation of the natural log of daily returns over the past 30 days.'}

folder = '../../data_gather/crypto/coin_metrics/'

crypto_df_list = {}

for crypto in ['btc', 'eth', 'doge', 'ltc', 'bch', 'etc', 'xmr', 'dash']:
    df = pd.read_csv(folder + crypto + '.csv')
    crypto_df_list[crypto] = df

crypto_attr_df_list = {}

for col_name in columns.keys():
    temp = []
    for crypto, df in crypto_df_list.items():
        if col_name in df.columns:
            temp.append(pd.DataFrame({'date': df['date'], crypto: df[col_name]}))
    attr_df = reduce(lambda df1, df2: pd.merge(df1, df2, on=['date'], how='inner'), temp)
    attr_df.dropna(inplace=True)
    crypto_attr_df_list[col_name] = attr_df

for attr, df in crypto_attr_df_list.items():
    df.to_csv(f'../../data/coin_metrics/{attr}.csv', index=False)
