---
title: "Youtube Comments ARM"
author: "Jingsong, GAO"
date: "2021/10/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up
```{r, message=FALSE}
library(arules)
library(arulesViz)
library(dplyr)
library(igraph)
library(networkD3)
library(visNetwork)
library(tidyverse)
```

## Data
```{r warning=FALSE}
dat = read.transactions("../data/transaction.txt", format = "basket", sep=",")
```

## Apriori 2
```{r}
rules2 = apriori(dat, parameter = list(supp = 20/120000, conf = 0.5, target = "rules", minlen=2, maxlen=2))
```

```{r}
write.csv(DATAFRAME(rules2), "arules2.csv")
write.csv(DATAFRAME(head(rules2, by = "support", n = 15)), "arules2_sup_top15.csv")
write.csv(DATAFRAME(head(rules2, by = "confidence", n = 15)), "arules2_conf_top15.csv")
write.csv(DATAFRAME(head(rules2, by = "lift", n = 15)), "arules2_lift_top15.csv")
```

```{r}
rules3 = apriori(dat, parameter = list(supp = 20/120000, conf = 0.5, target = "rules", minlen=3))
```

```{r}
write.csv(DATAFRAME(rules3), "arules3.csv")
write.csv(DATAFRAME(head(rules3, by = "support", n = 15)), "arules3_sup_top15.csv")
write.csv(DATAFRAME(head(rules3, by = "confidence", n = 15)), "arules3_conf_top15.csv")
write.csv(DATAFRAME(head(rules3, by = "lift", n = 15)), "arules3_lift_top15.csv")
```

## Frequent Item

```{r}
freqitem2 = eclat(dat, parameter = list(supp = 20/120000, minlen=2, maxlen=2))
```
```{r}
write.csv(DATAFRAME(freqitem2), "freqitem2.csv")
write.csv(DATAFRAME(head(freqitem2, by = "support", n = 15)), "freqitem2_sup_top15.csv")
```

```{r}
freqitem3 = eclat(dat, parameter = list(supp = 20/120000, minlen=3))
```

```{r}
write.csv(DATAFRAME(freqitem3), "freqitem3.csv")
write.csv(DATAFRAME(head(freqitem3, by = "support", n = 15)), "freqitem3_sup_top15.csv")
```

## Special Apriori
```{r}
rules.all = apriori(dat, parameter = list(supp = 20/120000, conf = 0.5, minlen=2))
gpu = c("nvidia", "gpu", "rtx", "gtx", "radeon")
rules.gpu = subset(rules.all, subset = lhs %in% gpu | rhs %in% gpu)
write.csv(DATAFRAME(rules.gpu), "arules_gpu.csv")
```
```{r}
gpu = c("nvidia", "graphic", "gpu", "rtx", "gtx", "radeon")
rules.gpu = subset(rules.all, subset = lhs %in% gpu | rhs %in% gpu)
write.csv(DATAFRAME(rules.gpu), "arules_gpu.csv")
```

```{r}
cpu = c("cpu", "processor", "ryzen", "core", "i5", "i7", "i9")
rules.cpu = subset(rules.all, subset = lhs %in% cpu | rhs %in% cpu)
write.csv(DATAFRAME(rules.cpu), "arules_cpu.csv")
```


```{r}
phone = c("iphone", "android", "xiaomi", "huawei", "samsung")
rules.phone = subset(rules.all, subset = lhs %in% phone | rhs %in% phone)
write.csv(DATAFRAME(rules.phone), "arules_phone.csv")
```

```{r}
company = c("apple", "facebook", "google", "microsoft", "youtube")
rules.company = subset(rules.all, subset = lhs %in% company | rhs %in% company)
write.csv(DATAFRAME(rules.company), "arules_company.csv")
```

```{r}
host = c("linus", "riley")
rules.host = subset(rules.all, subset = lhs %in% host | rhs %in% host)
write.csv(DATAFRAME(rules.host), "arules_host.csv")
```

```{r}
other = c(gpu, cpu, phone, company)
rules.other = apriori(dat, parameter = list(supp = 20/120000, conf = 0.5, minlen=2),  appearance = list(none = other))
write.csv(DATAFRAME(rules.other), "arules_other.csv")
```

```{r}
gen_nodes_n_edges = function(my.rules, degree_threshold=20) {
    df_rules = DATAFRAME(my.rules) %>%
      rowid_to_column("rules") %>%
      mutate(rules = paste("Rules", rules), RHS = str_remove_all(string = RHS, pattern = "[{}]"))
    df_items = df_rules %>%
      mutate(LHS = str_remove_all(string = LHS, pattern = "[{}]")) %>%
      separate(col = LHS, into = c(paste0("item_", 1:3)), sep = ",") %>%
      pivot_longer(cols = c(item_1, item_2, item_3), names_to = "antecedent", values_to = "item") %>%
      select(rules, antecedent, item, RHS, everything()) %>%
      filter(is.na(item) == FALSE)
    nodes = data.frame(name = unique(c(df_items$item, df_items$RHS, df_items$rules))) %>%
      rowid_to_column("id") %>%
      mutate(group = ifelse(str_detect(name, "Rules"), "A", "B"),
             label = name,
             value = c(rep(NA, n_distinct(c(df_items$item, df_items$RHS))), df_rules$lift),
             support = c(rep(NA, n_distinct(c(df_items$item, df_items$RHS))), df_rules$support),
             confidence = c(rep(NA, n_distinct(c(df_items$item, df_items$RHS))),df_rules$confidence),
             shape = ifelse(group == "A", "circle", "box"),
             color = ifelse(group == "A", "lightblue", "lightgreen"),
             title = ifelse(test = group == "A", yes = paste(name, "<br> Lift:", round(value, 2), "<br> Confidence:", round(confidence, 2), "<br> Support:", round(support, 2)), no = as.character(name)))
    
    edges = data.frame(from = df_items$item, to = df_items$rules) %>%
        bind_rows(data.frame(from = df_rules$rules, to = df_rules$RHS)) %>%
        left_join(nodes, by = c(from = "name")) %>% select(id, to) %>%
        rename(from = id) %>% left_join(nodes, by = c(to = "name")) %>%
        select(from, id) %>%
        rename(to = id) %>%
        mutate(color = ifelse(to <= degree_threshold, "red", "green"))
    return(list(nodes = nodes, edges = edges))
}
```

## igraph
```{r}
vis.company = plot(rules.company, method = "graph", control = list(verbose = FALSE),
     measure = "lift", shading = "confidence", engine = "htmlwidget")
htmlwidgets::saveWidget(vis.company, "vis/igraph.html", selfcontained = TRUE)
```



## networkD3
```{r}
graph.gpu = gen_nodes_n_edges(rules.gpu, degree_threshold = 10)
edges_d3 = mutate(graph.gpu$edges, from = from - 1, to = to - 1) %>%
  mutate(value = 1)
nodes_d3 = mutate(graph.gpu$nodes, id = id - 1)
vis.gpu = forceNetwork(Links = edges_d3, Nodes = nodes_d3, Source = "from",
             Target = "to", NodeID = "label", Group = "group",
             Value = "value", arrows = T, Nodesize = "value",
             colourScale = JS("d3.scaleOrdinal(d3.schemeCategory10);"),
             linkColour = edges_d3$color, opacity = 0.8,
             fontSize = 24, fontFamily = "Roboto Condensed",
             zoom = TRUE)
saveNetwork(vis.gpu, "vis/networkD3.html", selfcontained = TRUE)
```

## VisNetwork
```{r}
graph.host = gen_nodes_n_edges(rules.host, degree_threshold=10)
vis.host = visNetwork(nodes = graph.host$nodes, edges = graph.host$edges, height = "500px", width = "100%") %>%
    visEdges(arrows = "to") %>%
    visOptions(highlightNearest = T) %>%
    visInteraction(tooltipStyle = "position: fixed; visibility: hidden; 
                   padding: 5px; white-space: nowrap;
                   font-size: 18px; color: black;
                   background-color: white; border-color: orange")
visSave(vis.host, "vis/VisNetwork.html", selfcontained = TRUE, background = "white")
```


## Sankey
```{r}
graph.cpu = gen_nodes_n_edges(rules.cpu, degree_threshold=10)
nodes_d3 <- mutate(graph.cpu$nodes, id = id - 1)
edges_d3 <- mutate(graph.cpu$edges, from = from - 1, to = to - 1) %>%
    mutate(value = 1)
vis.cpu = sankeyNetwork(Links = edges_d3, Nodes = nodes_d3,
              Source = "from", Target = "to",
              NodeID = "label", Value = "value",
              colourScale = JS("d3.scaleOrdinal(d3.schemeCategory10);"),
              fontSize = 24, fontFamily = "Roboto Condensed")
saveNetwork(vis.cpu, "vis/Sankey.html", selfcontained = TRUE)
```








